import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './component/Navbar';
import { ThemeProvider } from '@/app/component/theme-provider';
import Baner from './component/Baner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
     title: 'Create Next App',
     description: 'Generated by create next app',
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html lang="en" suppressHydrationWarning>
               <body className={`${inter.className}  antialiased`}>
                    <ThemeProvider
                         attribute="class"
                         defaultTheme="system"
                         enableSystem
                         disableTransitionOnChange
                    >
                         <nav className="w-full">
                              <Navbar />
                         </nav>
                         <div>
                              <Baner />
                         </div>
                         <main>{children}</main>
                         <footer>Footer</footer>
                    </ThemeProvider>
               </body>
          </html>
     );
}
